### ISSUE TITLE
sbatch options with no value

### ISSUE THREAD

**Issue by jmrgonza** [uwefladrich/scriptengine-tasks-hpc#27]
I am trying to use an option with no value (`--exclusive`) in the `hpc.slurm.sbatch` task. I have tried to add it to the scriptengine context as in this example:
```
- base.context:
    job:
      slurm:
        sbatch:
          opts:
            partition: "desa"
            mem: !noparse "0"
            exclusive:
```
This generates an `sbatch.tmp.yml` file with this content:
```- base.context:
    _: &SBATCH_OPTS {'partition': 'desa', 'mem': '0', 'exclusive': None, 'time': '12:00:00', 'output': 'CJ02.log', 'job-name': 'ECE4_CJ02', 'ntasks': 256, 'nodes': 2}
    _: &SBATCH_EXTRA
      hetjob_spec:
      sbatch_command: sbatch
- hpc.slurm.sbatch:
    <<: *SBATCH_OPTS
    <<: *SBATCH_EXTRA
```
but it seems that the `None` value is afterwards converted into a string that causes an error later

```
2024-02-07 09:33:28 ERROR [se.task:hpc.slurm.sbatch <fc41ab4036>] SLURM sbatch error: Command '['sbatch', '--parsable', '--partition', 'desa', '--mem', '0', '--exclusive', 'None', '--time', '12:00:00', '--output', 'CJ02.log', '--job-name', 'ECE4_CJ02', '--ntasks', '256', '--nodes', '2', '--', '/perm/clim/clw/ecearth4/virtualenv/bin/se', '--loglevel=debug', 'user-config-example.yml', 'cirrus.yml', 'experiment-config-example.yml', 'scriptlib/main.yml']' returned non-zero exit status 1.
```

This is the error trace:
```
Traceback (most recent call last):
  File "/perm/clim/clw/ecearth4/virtualenv/bin/se", line 8, in <module>
    sys.exit(main())
  File "/perm/clim/clw/ecearth4/virtualenv/lib/python3.9/site-packages/scriptengine/cli/se.py", line 166, in main
    context["se"]["instance"].run(script, context)
  File "/perm/clim/clw/ecearth4/virtualenv/lib/python3.9/site-packages/scriptengine/engines/simple_script_engine.py", line 69, in run
    context_update = self._guarded_run(todo, local_context)
  File "/perm/clim/clw/ecearth4/virtualenv/lib/python3.9/site-packages/scriptengine/engines/simple_script_engine.py", line 61, in _guarded_run
    raise error
  File "/perm/clim/clw/ecearth4/virtualenv/lib/python3.9/site-packages/scriptengine/engines/simple_script_engine.py", line 29, in _guarded_run
    return runner.run(context)
  File "/perm/clim/clw/ecearth4/virtualenv/lib/python3.9/site-packages/scriptengine/tasks/core/timing.py", line 56, in wrap_timed
    return func(self, context)
  File "/perm/clim/clw/ecearth4/virtualenv/lib/python3.9/site-packages/scriptengine/tasks/base/include.py", line 71, in run
    context_update = local_context["se"]["instance"].run(script, local_context)
  File "/perm/clim/clw/ecearth4/virtualenv/lib/python3.9/site-packages/scriptengine/engines/simple_script_engine.py", line 69, in run
    context_update = self._guarded_run(todo, local_context)
  File "/perm/clim/clw/ecearth4/virtualenv/lib/python3.9/site-packages/scriptengine/engines/simple_script_engine.py", line 61, in _guarded_run
    raise error
  File "/perm/clim/clw/ecearth4/virtualenv/lib/python3.9/site-packages/scriptengine/engines/simple_script_engine.py", line 29, in _guarded_run
    return runner.run(context)
  File "/perm/clim/clw/ecearth4/virtualenv/lib/python3.9/site-packages/scriptengine/tasks/core/timing.py", line 56, in wrap_timed
    return func(self, context)
  File "/perm/clim/clw/ecearth4/virtualenv/lib/python3.9/site-packages/scriptengine/tasks/base/include.py", line 71, in run
    context_update = local_context["se"]["instance"].run(script, local_context)
  File "/perm/clim/clw/ecearth4/virtualenv/lib/python3.9/site-packages/scriptengine/engines/simple_script_engine.py", line 69, in run
    context_update = self._guarded_run(todo, local_context)
  File "/perm/clim/clw/ecearth4/virtualenv/lib/python3.9/site-packages/scriptengine/engines/simple_script_engine.py", line 61, in _guarded_run
    raise error
  File "/perm/clim/clw/ecearth4/virtualenv/lib/python3.9/site-packages/scriptengine/engines/simple_script_engine.py", line 29, in _guarded_run
    return runner.run(context)
  File "/perm/clim/clw/ecearth4/virtualenv/lib/python3.9/site-packages/scriptengine/tasks/core/timing.py", line 56, in wrap_timed
    return func(self, context)
  File "/perm/clim/clw/ecearth4/virtualenv/lib/python3.9/site-packages/scriptengine_hpc/slurm.py", line 92, in run
    raise ScriptEngineTaskRunError
scriptengine.exceptions.ScriptEngineTaskRunError
```

**Comment by uwefladrich** [comment]
As a first step to reproduce, I tried the following script:
```yaml
- hpc.slurm.sbatch:
    account: my_account
    output: test.out
    mem: 0
    exclusive:
- base.echo:
    msg: Hi!
```
That works on our machine as it should.

So it seems that this is not a problem of the ``hpc.slurm.sbatch`` task, which behaves as expected. It appears to be a problem of the actual scripts (and templates) setting up the task in the ECE4 runtime environment. You could try to run the script above on your machine in order to reproduce.

**Comment by jmrgonza** [comment]
You are right, I tested with the following script and the batch job executed fine:
```
- hpc.slurm.sbatch:
    partition: desa
    output: test.out
    mem: 0
    exclusive:
- base.echo:
    msg: Hi!
```
So, I guess I should close the issue here.

EDIT:
It also works with this script:
```
- hpc.slurm.sbatch:
    partition: desa
    output: test.out
    mem: 0
    exclusive: null
- base.echo:
    msg: Hi!
```
but not with this one:
```
- hpc.slurm.sbatch:
    partition: desa
    output: test.out
    mem: 0
    exclusive: None
- base.echo:
    msg: Hi!
```

**Comment by uwefladrich** [comment]
Yes, the YAML representation of the ``None`` type is the string ``null``, which is why the last script does not work.

Actually, I have already seen a very similar issue in another context and I have a vague idea what to do about it. I will follow it up and take this example also into account.
