### ISSUE TITLE
Package not found error

### ISSUE THREAD

**Issue by uwefladrich** [uwefladrich/scriptengine-tasks-hpc#4]
Running `se` with the `scriptengine-tasks-hpc` package installed results in the following error:
```
se --help
Traceback (most recent call last):
  File "[...]/bin/se", line 8, in <module>
    sys.exit(main())
  File "[...]/lib64/python3.8/site-packages/scriptengine/cli/se.py", line 109, in main
    parsed_args = parse_cmd_line_args()
  File "[...]/lib64/python3.8/site-packages/scriptengine/cli/se.py", line 52, in parse_cmd_line_args
    ', '.join(scriptengine.tasks.core.loader.load().keys()))
  File "[...]/lib64/python3.8/site-packages/scriptengine/tasks/core/loader.py", line 21, in load
    loaded_tasks[ep.name] = ep.load()
  File "[...]/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "[...]/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'scriptengine_hpc'
```

**Comment by uwefladrich** [comment]
... the reason being that an `__init__.py` file is missing in the main `scriptengine_hpc` directory, which prevents `setuptools.find_packages()` from finding it automatically when building the package.
